### ISSUE TITLE
Downshifting particles shader

### ISSUE THREAD

**Issue by vkuchinov** [spite/polygon-shredder#8]
Hi, Jaume!

Why do you have particle position multiplied by 18?

```
var positionsLength = curlNoiseModel.width * curlNoiseModel.height * 3 * 18;
var positions = new Float32Array( positionsLength );

var p = 0;

for( var j = 0; j < positionsLength; j += 3 ) {

    positions[ j ] = p
    positions[ j + 1 ] = Math.floor( p / 18 )
    positions[ j + 2 ] = p % 18
    p++;

}

geometry.addAttribute( 'position', new THREE.BufferAttribute( positions, 3 ) );
```

And can you give me a hint how to downshift particles shader for simple flat 2D sprite, like https://bl.ocks.org/vkuchinov/0942e561a993ce91d789299b44adfee0?

**Comment by spite** [comment]
Because each cube is made up of 18 vertices: 3 faces, 2 triangles each, 3 vertices per triangle: 3 * 2 * 3.
Each cube is really a half cube, and faces are shifted to face the camera, because the rear part is not necessary. I'm not sure it adds a lot of improvement. That's why I call the method "pseudoinstancing".

I'm not sure what you're asking about downshifting, though. You're using Points in your example, so that's quite a different case.

**Comment by vkuchinov** [comment]
I'm asking if it's possible to decrease position attribute by 18, so there would be just one vertex per particle and render it as a 2D sprite which would be always looking to camera.

**Comment by spite** [comment]
You mean in my code? Yes, you could do that, but it would look completely different, and most of the code wouldn't make sense. But yes, there's billboard particle systems with curl noise out there. In fact, they're the "default" way of doing them...

**Comment by vkuchinov** [comment]
Cheers.
